AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template to create Transit Gateway and share via Resource Access Manager 

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Transit Gateway Configuration
        Parameters:
          - pASNTGW
          - pCustomerName
      - Label:
          default: Organization Configuration
        Parameters:
          - pOrgId
          - pMasterAccountId

Parameters:
  pOrgId: 
    Type: String
    Description: Enter Organization Id (e.g. o-12345) if Organization sharing is enabled
    Default: o-65r2o73zh8
  pMasterAccountId:
    Type: String
    Description: Account Id of master account in AWS Organization
    Default: 822980120791
  pASNTGW:
    Type: Number
    Default: 65000
    Description: ASN of Transit Gateway
  pTGWShareName:
    Type: String
    Default: TGW-USE1
  pCustomerName:
    Type: String
    Default: Study


Resources:
  rTransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: !Ref pASNTGW
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
      - Key: Name
        Value: !Ref pCustomerName
  
  rTGWShare:
    Type: "AWS::RAM::ResourceShare"
    Properties:
      AllowExternalPrincipals: true
      Name: !Ref pTGWShareName
      Principals: 
        - !Sub 'arn:aws:organizations::${pMasterAccountId}:organization/${pOrgId}'
      ResourceArns: 
        - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${rTransitGateway}'

Outputs:
  oTransitGateway:
      Description: Static Transit Gateway Id
      Value: !Ref rTransitGateway
      Export:
          Name: TransitGatewayId