Parameters:  
  ShareWithOrg: 
    Type: String
    Default: false
    Description: Enable sharing with all AWS Accounts in an AWS Organization
    AllowedValues: 
      - true
      - false
  OrgId: 
    Type: String
    Description: Enter Organization Id (e.g. o-12345) if Organization sharing is enabled
  MasterAccountId:
    Type: String
    Description: Account Id of master account in AWS Organization

Conditions:
  EnableRAM: !Equals
      - !Ref ShareWithOrg
      - true

Resources:
  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: 65000
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
  
  TgwShare:
    Type: "AWS::RAM::ResourceShare"
    DependsOn: TransitGateway
    Condition: EnableRAM
    Properties:
      AllowExternalPrincipals: true
      Name: TGW-Org-Share
      Principals: 
        - !Sub 'arn:aws:organizations::${MasterAccountId}:organization/${OrgId}'
      ResourceArns: 
        - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${TransitGateway}'

Outputs:
    TransitGateway:
        Description: Static Transit Gateway Id
        Value: !Ref TransitGateway
        Export:
            Name: TransitGatewayId