#Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of this
#software and associated documentation files (the "Software"), to deal in the Software
#without restriction, including without limitation the rights to use, copy, modify,
#merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
#permit persons to whom the Software is furnished to do so.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: '2010-09-09'

Description: Creates a Service Catalog portfolio for self-service network products.

Parameters:
  pPortfolioName:
    Type: String
    Default: Self-Service Network Portfolio

  pVpcProductKey:
    Type: String
    Description: The full S3 location where the VPC product template is uploaded to.
    Default: https://marketplace-sa-resources-ct-us-east-1.s3.amazonaws.com/ct-blogs-content/product-vpc.cf.yml

  pVpcLaunchRoleName:
    Type: String
    Description: The launch role name that is used to launch the VPC product in the spoke accounts.


Resources:

##### Portfolio Resources #####

  rMasterPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      AcceptLanguage: en
      Description: Portfolio for network products
      DisplayName: !Ref pPortfolioName
      ProviderName: AWS

##### Product Resources #####

  rVpcProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      AcceptLanguage: en
      Description: This product builds a standardized VPC.
      Distributor: AWS
      Name: VPC
      Owner: AWS
      ProvisioningArtifactParameters:
        - Description: This is version 1.0 of the AWS VPC product.
          Name: Version - 1.0
          Info:
            LoadTemplateFromURL: !Ref pVpcProductKey

##### Product Launch Role Constraints #####

  rVpcProductLaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      AcceptLanguage: en
      Description: The launch role constraint used to restrict who can launch the VPC product from the portfolio.
      LocalRoleName: !Ref pVpcLaunchRoleName
      PortfolioId: !Ref rMasterPortfolio
      ProductId: !Ref rVpcProduct

##### Portfolio / Product Associations ##### 
  
  rVpcProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      AcceptLanguage: en
      PortfolioId: !Ref rMasterPortfolio
      ProductId: !Ref rVpcProduct


Outputs:
  oMasterPortfolioId:
    Description: The master portfolio ID that was created
    Value: !Ref rMasterPortfolio
    Export:
      Name: MASTER-NTWK-PORTFOLIO-ID

  oVpcProductId:
    Description: VPC product ID
    Value: !Ref rVpcProduct
    Export:
      Name: VPC-PRODUCT-ID

  oVpcProductName:
    Description: VPC Product Name
    Value: !GetAtt rVpcProduct.ProductName
    Export:
      Name: VPC-PRODUCT-NAME